### ISSUE TITLE
poor inference results.

### ISSUE THREAD

**Issue by ghvision** [zhijieshen-bjtu/DOPNet#1]
Thank you for your nice work and early code release!

But, when I run your inference code for my custom data with your pretrained model, the result was very poor, even unreasonable.

So ,I tested again with pano_s2d3d data, but the result was same. 

They seem not to be trained.

![pano_abmykjljhuxymn_pred](https://user-images.githubusercontent.com/115695283/224938837-1b310236-4d27-4775-b493-5797b7854d99.png)
![pano_afpcovbiswnzlg_pred](https://user-images.githubusercontent.com/115695283/224938967-a93abf4a-a3d9-463f-9114-d785cf574d9c.png)

Do you think I mistook to run your inference? 

Please notify me your opinion.

Thanks!

**Comment by zhijieshen-bjtu** [comment]
Ensure that you have put the pre-trained models in the corresponding folder and loaded it correctly.

**Comment by CBS5181** [comment]
@zhijieshen-bjtu Hi author, thanks for your early code release!
However, I have the same problem as @ghvision.
Both Matterport and ZInD results with pre-trained model seems to be incorrect.

- ZInD
![image](https://user-images.githubusercontent.com/35103220/230841122-2446c88b-e0fe-4972-ac31-26c418d2f46c.png)
![image](https://user-images.githubusercontent.com/35103220/230841257-fc0372a1-a696-4d6b-bdc3-67177f2e11c3.png)

- M3D
![image](https://user-images.githubusercontent.com/35103220/230841346-a4f72773-52b5-49fc-9925-56f1a33ae2cf.png)
![image](https://user-images.githubusercontent.com/35103220/230841485-f2ae2b49-d49e-4099-9afd-0de59c5b60d1.png)


Here is my command
```
// zind
python inference_ZInD.py --cfg src/my_config/zind.yaml --img_glob "/home/user/CBS/zind_test/data_preprocessed/*/*.jpg" --output_dir src/output --post_processing manhattan
// m3d
python inference_M3D.py --cfg src/my_config/mp3d.yaml --img_glob "/home/user/CBS/Matterport3D/panorama/data_preprocessed/*/*.jpg" --output_dir src/output --post_processing manhattan
```

**Comment by zhijieshen-bjtu** [comment]
Sorry for the inconvenience, my colleagues are checking the issues.

**Comment by zhijieshen-bjtu** [comment]
![pano_abmykjljhuxymn_pred](https://user-images.githubusercontent.com/48438062/230886525-b99f02fc-8568-4253-9169-49865826fe9a.png)

**Comment by zhijieshen-bjtu** [comment]
![pano_abmykjljhuxymn_pred](https://user-images.githubusercontent.com/48438062/230886587-810ef6b5-3c12-4e83-8399-430910987f49.png)
@ghvision We re-evaluate the posted image and get the correct result. Is your issue resolved?

**Comment by CBS5181** [comment]
> Sorry for the inconvenience, my colleagues are checking the issues.

Hi, author. Have you identified the issue yet?
