### ISSUE TITLE
weired inference results on ZInD and M3D.

### ISSUE THREAD

**Issue by CBS5181** [zhijieshen-bjtu/DOPNet#2]
Hi author, thanks for your early code release!
I have a response on another issue #1 , but the issue seems to have closed. 
I'm not sure if that issue has been resolved. So I posted this new issue.

I've tried to inference both Matterport and ZInD with pre-trained model, however the results seems to be incorrect.
Here is my command
```
// zind
python inference.py --cfg src/my_config/zind.yaml --img_glob "/home/user/CBS/zind_test/data_preprocessed/*/*.jpg" --output_dir src/output --post_processing manhattan
// m3d
python inference.py --cfg src/my_config/mp3d.yaml --img_glob "/home/user/CBS/Matterport3D/panorama/data_preprocessed/*/*.jpg" --output_dir src/output --post_processing manhattan
```
- ZInD 
![image](https://user-images.githubusercontent.com/35103220/231427260-4de65d8a-078c-4d77-8a7a-3cb634c4b601.png)

- M3D
![image](https://user-images.githubusercontent.com/35103220/231427314-94476049-f5d0-4283-aa68-29243b7de1ec.png)

The result of demo image with command beblow is also incorrect.
```
python inference.py --cfg src/my_config/mp3d.yaml --img_glob src/demo/demo1.png --output_dir src/output --post_processing manhattan
```
- Demo image
![image](https://user-images.githubusercontent.com/35103220/231426658-ef1a2617-68fd-476f-95fd-0112f278a9d7.png)

I think this code should be similar to LGT-Net, but I don't know why it still produces incorrect results after placing the pretrained model in the right place.
I would appreciate it if you could check the issues as soon as possible.

**Comment by zhijieshen-bjtu** [comment]
Hi, the released trained model may be wrong, are there the same issues when you evaluate the other two datasets?

**Comment by zhijieshen-bjtu** [comment]
We have checked the released code without finding errors. Even so, we update the code with our re-evaluated version.

**Comment by CBS5181** [comment]
> We have checked the released code without finding errors. Even so, we update the code with our re-evaluated version.

`dataset = MP3DDataset(root_dir='/opt/data/private/360Layout/Datasets/mp3d', mode='test')`

Can I just use `inference()` with `--img.glob` command without creating the MP3DDataset or ZindDataset?
https://github.com/zhijieshen-bjtu/DOPNet/blob/cc340ae71e5ddd7187969e8e5610b6897abd79f4/inference.py#L167-L185
```python=
// ...
model, _, _, _ = build_model(config, logger)
os.makedirs(args.output_dir, exist_ok=True)
img_paths = sorted(glob.glob(args.img_glob, recursive=True))
inference()
```
I have tried the updated code, but the result is still werid.
![image](https://user-images.githubusercontent.com/35103220/231941947-18a5b97f-5a73-4a5d-a438-303e9eebfc36.png)

**Comment by zhijieshen-bjtu** [comment]
We run inference() with --img.glob command, it also works well (the demo and its prediction results.).

**Comment by CBS5181** [comment]
> We have checked the released code without finding errors. Even so, we update the code with our re-evaluated version.

Sorry, I forgot update the pretrained model. The results are correct now!
Thanks.
![image](https://user-images.githubusercontent.com/35103220/232210031-aa4c4c98-b1fa-404a-9d85-9c8de8f9d1bb.png)
