### ISSUE TITLE
wired inference results

### ISSUE THREAD

**Issue by zjngjng** [zhijieshen-bjtu/DOPNet#3]
Thanks the authors for releasing the codes! I have got very poor results similarly as discussed in this thread https://github.com/zhijieshen-bjtu/DOPNet/issues/1. I also tried the most recently updated codes, which didn't work neither. Could you please take a look again? Are the shared models correct? Thanks.

**Comment by zhijieshen-bjtu** [comment]
It seems that the same issue posed by @CBS5181 has been resolved, how about you?

**Comment by marisancans** [comment]
Im having the same issue. I even had to edit code in some places
![image](https://user-images.githubusercontent.com/16538903/233033000-5d27c0e2-2ea1-4567-b6db-6ff52c7f134d.png)

**Comment by marisancans** [comment]
ok, this is funny. If anyone has wierd results, please download the checkpoints! They are empty folders by default and doesnt contain *.pth files. The only auto download thing is resnet I think from torchvision.
Authors should check if ckpt_dir is present or at least put some warning message or something.
![image](https://user-images.githubusercontent.com/16538903/233035470-54a30a97-e5db-41f7-a836-b5575d833757.png)

**Comment by zjngjng** [comment]
> It seems that the same issue posed by @CBS5181 has been resolved, how about you?

Yes, this issue has been resolved. The pretrained models were not downloaded correctly, I re-downloaded the models and it worked! Thanks!
